# Generated by Django 5.0.1 on 2024-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Child'), ('O', 'Other')], max_length=200, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='image_appointment',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/customers_profile', verbose_name='image_appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='phone_number'),
        ),
    ]
